@echo off
tutorial.txt
pip install playsound
pip install appdirs                
pip install asgiref                  
pip install auto-translation         
pip install beautifulsoup4           
pip install certifi                  
pip install cfgv                     
pip install chardet  
pip install chromedriver-binary-auto
pip install click                    
pip install colorama                 
pip install comtypes                 
pip install configparser             
pip install crayons                  
pip install distlib                                    
pip install fake-useragent           
pip install filelock                 
pip install Flask                    
pip install gcloud                   
pip install google
pip install apis-common-protos 
pip install googletrans              
pip install gTTS                     
pip install h11                     
pip install h2                       
pip install hpack                   
pip install hstspreload             
pip install httpcore               
pip install httplib2              
pip install httpx                  
pip install hyperframe             
pip install identify 
pip install inna              
pip install itsdangerous            
pip install Jinja2                  
pip install jws                    
pip install lxml                   
pip install MarkupSafe               
pip install MouseInfo                         
pip install nodeenv                 
pip install oauth2client            
pip install packaging               
pip install pi                      
pip install Pillow                 
pip install pip                     
pip install playsound               
pip install pluggy                 
pip install pre-commit             
pip install protobuf               
pip install py                       
pip install pyasn1                  
pip install pyasn1-modules           
pip install PyAudio                  
pip install PyAutoGUI                
pip install pycryptodome            
pip install PyGetWindow              
pip install PyMsgBox               
pip install pip install pynput                 
pip install pyparsing                
pip install pyperclip              
pip install pypiwin32                
pip install Pyrebase                 
pip install PyRect 
pip install PySreeze               
pip install python-jwt             
pip install pyttsx3                
pip install PyTweening 
pip install pytz             
pip install pywin32                
pip install PyYAML                  
pip install random-xe               
pip install random2                  
pip install requests                 
pip install requests-toolbelt        
pip install rfc3986                   
pip install rsa                     
pip install selenium                 
pip install setuptools               
pip install simpleaudio             
pip install six                     
pip install sniffio                  
pip install soupsieve                
pip install SpeechRecognition       
pip install sqlparse                
pip install text-to-speech                   
pip install toml                     
pip install tox                                     
pip install urllib3                 
pip install virtualenv              
pip install webdriver-manager       
pip install Werkzeug                
pip install youtube-search
pip install wikipedia
pip install kivi
pause